name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter user name'
        required: true
        default: 'Manazar'
      environments:
        description: 'Choose the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:

      - name: Print Hello World
        run: echo "Hello World!"

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Echo User Inputs
        run: |
          echo "Hello, ${{ inputs.username }}!"
          echo "Selected Environment: ${{ inputs.environments }}"

      - name: List Repository Files
        run: |
          echo "Following repository: ${{ github.repository }}"
          pwd
          tree
