name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter user name'
        required: true
        default: 'Manazar'
      environments:
        description: 'Choose the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod
      

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      
      - run: echo "Hello World!"
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: list the files in repositories
        run: |
         echo following respository ${{ github.repository }}
         pwd
         tree

    
