name: Matrix testing
on:
  push:
    branches:
      - main
jobs:
  matrix-test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,macos-latest]
        node: [14, 16, 18]
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: {{ matrix.node}}
      - name: check the node version
        run: node -v
    
      
