name: Matrix Testing

on:
  push:
    branches:
      - main

jobs:
  matrix-test:
    runs-on: ${{ matrix.os }}  # The matrix will create a separate job for each OS in the list
    strategy:
      matrix:
        os: [ubuntu-latest]  # Runs the job on each OS
        node: [18]  # Runs the job with each Node.js version

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}  # Uses the Node.js version from the matrix

      - name: Check Node.js version and repo details
        run: |
          node -v
          echo "Repository: ${{ github.repository }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Triggered by SHA: ${{ github.sha }}"


      
